nettside/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("logg-inn/", views.login_user, name="login"),
    path("registrer/", views.register, name="register"),
    path("logg-ut/", views.logout_user, name="logout"),
]



""" accounts/ login/ [name='login']
accounts/ logout/ [name='logout']
accounts/ password_change/ [name='password_change']
accounts/ password_change/done/ [name='password_change_done']
accounts/ password_reset/ [name='password_reset']
accounts/ password_reset/done/ [name='password_reset_done']
accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/ reset/done/ [name='password_reset_complete']"""

nettside/nettside/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("quiz.urls")),
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),
]

nettside/quiz/urls.py
from django.urls import path
from . import views
from . import api


app_name = 'quiz'

urlpatterns = [
    path(r'', views.quizside, name='quiz'),
    path(r'quiz/', views.quizcode, name='quizcode'),
    path(r'quiz/lag-quiz/', views.CreateQuiz.as_view(), name='create_quiz'),
    path(r'quiz/<int:quiz_id>/', views.play_quiz, name='play_quiz'),
    path(r'quiz/<int:quiz_id>/api/', api.QuizAPI.as_view(), name='play_quiz_api'),
]

nettside/accounts/models.py
from uuid import uuid4
from django.db import models
from django.contrib.auth.models import AbstractUser
from quiz.models import Quizark

class User(AbstractUser):
    favoritter = models.ManyToManyField(Quizark)

class Player(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    right = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    time_start = models.DateTimeField(auto_now_add=True)
    temporary = models.BooleanField(default=False)
    username = models.CharField(default="tempuser", max_length=100)


    def __str__(self):
        if self.user:
            return str(self.user)
        return self.uuid.hex

nettside/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

class CreateUserForm(UserCreationForm):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Brukernavn'}))
    password1 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Passord'}))
    password2 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Gjenta passord'}))
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

class LogInForm(AuthenticationForm):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'autofocus': True, 'placeholder': 'Brukernavn'}))
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password','placeholder': 'Passord'}))

    class Meta:
        model = User
        fields = ('username', 'password')

nettside/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import CreateUserForm, LogInForm
from time import sleep

# Create your views here.
def register(request):
    template_name = "accounts/register.html"
    if request.user.is_authenticated:
        messages.warning(request, "Du er allerede logget inn, for å registrere en ny bruker må du først logge deg ut")
        prev_page = request.META.get('HTTP_REFERER')
        if not prev_page:
            return redirect("quiz:quiz")
        return redirect(prev_page)
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Brukeren {username} er laget")
            login(request, user)
            return redirect("quiz:quiz")

        else:
            return render(request, template_name, {"form":form})

    form = CreateUserForm()
    return render(request, template_name, {"form":form})


def login_user(request):
    if request.user.is_authenticated:
        messages.warning(request, "Du er allerede logget inn, vil du logge inn som en annen bruker må du først logge deg ut")
        prev_page = request.META.get('HTTP_REFERER')
        if not prev_page:
            return redirect("quiz:quiz")
        return redirect(prev_page)
    if request.method == 'POST':
        form = LogInForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Du er nå logget inn som {username}")
                redirect_url = request.GET.get('next', 'quiz:quiz')
                return redirect(redirect_url)
            else:
                messages.error(request, "Brukeren finnes allerede")
        else:
            messages.error(request, "Feil brukernavn eller passord")

    form = LogInForm()
    return render(request, "accounts/login.html", {"form":form})


def logout_user(request):
    logout(request)
    # messages.info(request, f"Gratulerer {username}, du er nå logget ut")
    redirect_url = request.GET.get('next', 'quiz:quiz')
    return redirect(redirect_url)

nettside/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock css %}

{% block content %}
<div class="user_container">
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field }}<br>
        {% endfor %}

        <img src="{% static 'images/logo.png' %}"width="50" height="50"></br>
        <button type="submit">Logg inn</button>
    </form>
    <span><a href="{% url 'accounts:register' %}"><strong>Registrer deg her</strong></a>!</span>
</div>
{% endblock %}

nettside/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock css %}

{% block content %}

<div class="user_container">
    <form method="POST">
        {% csrf_token %}

        {% for field in form %}
            {% if form.errors %}
                <div class="field-error">
                    {% for error in field.errors %}
                        <strong>{{ error|escape }}</strong><br>
                    {% endfor %}
                    {{ field }}
                </div>
            {% else %}
                {{ field }}<br>
            {% endif %}

        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="form-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}


        <br><img src="{% static 'images/logo.png' %}"width="50" height="50"></br>
        <button type="submit">Registrer</button>
    </form>
    <span>Har du allerede konto? <a href="{% url 'accounts:login' %}"><strong>Logg inn</strong></a> i steden for.</span>
</div>

{% endblock content %}