nettside/nettside/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("quiz.urls")),
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),
]

nettside/quiz/urls.py
from django.urls import path
from . import views
from . import api


app_name = 'quiz'

urlpatterns = [
    path(r'', views.quizside, name='quiz'),
    path(r'quiz/', views.quizcode, name='quizcode'),
    path(r'quiz/lag-quiz/', views.CreateQuiz.as_view(), name='create_quiz'),
    path(r'quiz/<int:quiz_id>/', views.play_quiz, name='play_quiz'),
    path(r'quiz/<int:quiz_id>/api/', api.QuizAPI.as_view(), name='play_quiz_api'),
]

nettside/quiz/models.py
from django.db import models
from .utils import file_parser

# Create your models here.
class Question(models.Model):
    question = models.CharField(max_length=500)
    answer = models.CharField(max_length=100)

    def __str__(self):
        return self.question

class Quizark(models.Model):
    title = models.CharField(max_length=100)
    file = models.FileField()
    question = models.ManyToManyField(Question, blank=True)
    playing_id = models.IntegerField(default=False)
    is_playing = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=False)

    def save(self, *args, **kwargs):
        super(Quizark, self).save(*args, **kwargs)
        questions = file_parser(self.file.name)
        for question, answer in questions.items():
            if not Question.objects.filter(question=question):
                new_question = Question(question=question, answer=answer)
                new_question.save()
                self.question.add(new_question)

    def __str__(self):
        return self.title

nettside/quiz/forms.py
from django import forms
from .models import Quizark
from random import randint

def random_user():
    adj = ["kul", "teit", "rar", "gul", "glittrende"]
    sub = ["pølse", "ku", "gris", "ape", "sykkel", "sko", "esel"]
    return adj[randint(0, len(adj)-1)].capitalize() + sub[randint(0, len(sub)-1)].capitalize()

class QuizCodeForm(forms.Form):
    # Må fikse bug her
    code = forms.IntegerField(label='Kode: ', min_value=100000, max_value=999999)
    username = forms.CharField(required=False, max_length="100", initial=random_user)


class QuizCreateForm(forms.Form):
    quizark = forms.ModelChoiceField(queryset=Quizark.objects.all())

nettside/quiz/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib import messages

from datetime import datetime
from random import randint

from accounts.models import Player
from .forms import QuizCodeForm, QuizCreateForm
from .models import Quizark

# Create your views here.
def quizside(request):
    return render(request, 'quiz/quizside.html')

def quizcode(request):
    if request.method == "POST":
        form = QuizCodeForm(request.POST)
        if form.is_valid():
            quiz_code = form.cleaned_data['code']
            if request.user.is_authenticated:
                print(request.user)
                player = Player.objects.create(username=request.user.username, user=request.user)
            else:
                randusername = form.cleaned_data['username']
                player = Player.objects.create(username=randusername, temporary=True)
            request.session["player"] = player.uuid.hex
            return redirect("quiz:play_quiz", quiz_id=quiz_code)


    form = QuizCodeForm()
    return render(request, 'quiz/quizcode.html', {"form": form})

def play_quiz(request, quiz_id):
    # Bør kanskje fikses litt?
    try:
        Player.objects.get(uuid=request.session["player"])
    except Player.DoesNotExist:
        raise PermissionDenied("Du har ingen bruker")
    if not request.session.get("is_playing") == quiz_id and request.session.get("is_playing"):
        messages.warning(request, f"Du spiller allerede en quiz")
        return redirect("quiz:quiz")
    request.session["is_playing"] = quiz_id
    return render(request, 'quiz/play_quiz.html')

class CreateQuiz(LoginRequiredMixin, View):
    template_name = "quiz/create_quiz.html"

    def create_quiz_code(self):
        # lager unik quiz kode ut ifra minuttene nå + 4 random tall
        minute = str(datetime.now().minute)
        four_random = ""
        for i in range(4):
            four_random += str(randint(0, 9))
        print(minute + four_random)
        return minute + four_random


    def get(self, request):
        form = QuizCreateForm()
        if request.user:
            fav_quizes = request.user.favoritter.all()
        else:
            fav_quizes = None

        quizes = Quizark.objects.all()
        return render(request, self.template_name, {'form': form, "favs": fav_quizes, "quizes": quizes})

    def post(self, request):
        form = QuizCreateForm(request.POST)

        if form.is_valid():
            selected_quiz_id = form.cleaned_data["quizark"].id
            quiz_id = self.create_quiz_code()
            print(selected_quiz_id)
            new_created_quiz = Quizark.objects.get(pk=selected_quiz_id)
            new_created_quiz.is_playing = True
            new_created_quiz.playing_id = quiz_id
            new_created_quiz.save()
            return redirect("quiz:play_quiz", quiz_id=quiz_id)

        return render(request, self.template_name, {'form': form})

nettside/quiz/templates/quiz/create_quiz.html
{% extends 'base.html' %}

{% block title %}
Lag ny quiz!
{% endblock title %}

{% block content %}
<div class="container">
    <h1>Lag en quiz!</h1>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
        {{ field }}
        {% endfor %}
        <button type="submit">Lag</button>
    </form>

    {% for quiz in favs %}
    {{ quiz }}
    {% endfor %}
    <hr>
    <h2>Alle quizene</h2>
    {% for quiz in quizes %}
    <h3>{{ quiz.title }}</h3>
    <strong>Quiz nr: {{ quiz.id }}</strong>
    <ul>
        {% for q in quiz.question.all|slice:":3"   %}
        <li>{{ q.question }}</li>
        {% endfor %}
    </ul>
    <button value="{{ quiz.id }}" class="choose">Velg</button>
    {% endfor %}
</div>
{% load static %}
<script src="{% static 'js/create_quiz.js' %}"></script>
{% endblock content %}

nettside/quiz/templates/quiz/play_quiz.html
{% extends 'base.html' %}

{% block title %}
Spiller quiz
{% endblock title %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/play_quiz.css' %}">
{% endblock css %}

{% block content %}
<h1>Quiz</h1>
<div id="container">

</div>
<script src="{% static 'js/quiz_api.js' %}"></script>
{% endblock content %}

nettside/quiz/templates/quiz/quizcode.html
{% extends 'base.html' %}
{% block title %}
Spill Quizing
{% endblock title %}

{% block content %}
<div class="container">
    <h1>Skriv inn koden for å spille quiz</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="code">Quizkoden: </label>
        {{ form.code }}<br>
        {% if not user.is_authenticated %}
        <label for="username">Midlertidig brukernavn: </label>
        {{ form.username }}<br>
        {% endif %}
        <button type="submit">Spill</button>
    </form>
</div>
{% endblock content %}

nettside/quiz/templates/quiz/quizside.html
{% extends 'base.html' %}

{% block title %}
Quizing - Hjem
{% endblock title %}

{% block content %}

<div class="container">
    <h1>Hei og velkommen til Quizing, dette er en test</h1>
    <a href="{% url 'quiz:quizcode' %}">Spill her!</a>
</div>
{% endblock content %}